### PR TITLE
Bump Scala version to match rocket-chip

### PR DESCRIPTION
**Pull request by grebe**

### CODE REVIEW

**Comment by aswaterman** [comment]
@grebe does this work with rocket-chip master?

**Comment by grebe** [comment]
Just built a fresh emulator using this PR, everything builds. `make run-fast` is running right now and looks OK so far.

**Comment by aswaterman** [comment]
Thanks.

**Comment by ucbjrl** [comment]
This breaks hardfloat's stand-alone testing. It includes a dependency on `chisel` (not `chisel3`) and we don't currently publish Scala 2.12 versions of `chisel`. Unfortunately, it looks non-trivial to update hardfloat's testing to something more `chisel3`-ish.

Just an FYI.

**Comment by ucbjrl** [comment]
That sounds doable.

**Comment by jackkoenig** [comment]
In https://github.com/freechipsproject/rocket-chip/pull/1431 the `++2.12.4` stuff allows us to hard override the Scala Version in hardfloats sbt file. Simply duplicating the build logic in rocket-chip but using 2.12 would probably be cleaner.

**Comment by jackkoenig** [comment]
Sorry for not being more clear. There were two thoughts in my previous comment:

1. This exact problem (Chisel 2 not being compiled for 2.12 thus the stand-alone tests not working with this type of change) is something I ran into in doing https://github.com/freechipsproject/rocket-chip/pull/1431. The solution I found was to add `++2.12.4` to all invocations of sbt which overrides all other versions (in particular, 2.11 in hardfloat). I couldn't find a way to do such overriding exclusively in rocket-chip's build.sbt file so that was the best I could come up with.

2. A better solution might just be to just define the chisel3 build description for hardfloat in rocket-chip's build.sbt. It's about as simple as it gets, so I don't think there's a lot of value in sharing the build description. In fact, my "solution" in https://github.com/freechipsproject/rocket-chip/pull/1431 probably causes more confusion than anything.

**Pull request merged**
